name: GitHub Actions Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests Automatically
        run: python -m unittest discover .